### ISSUE TITLE
cut command ends with: Failure: java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by wpchen** [alex-plekhanov/insvtools#1]
I tested the cut command on `sample.insv` and it failed with `Failure: java.nio.BufferOverflowException`. Complete output:

```
code/insvtools/target/release-package/insvtools-1.1-SNAPSHOT $ java -jar insvtools.jar cut --start-time=0.100 ../../../src/test/resources/sample.insv
InsvTools v.1.1-SNAPSHOT, start processing 'cut' command
Processing sample.insv -> sample.cut.insv
Failure: java.nio.BufferOverflowException

code/insvtools/target/release-package/insvtools-1.1-SNAPSHOT $ mvn --version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 21.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.3.1", arch: "aarch64", family: "mac"

code/insvtools/target/release-package/insvtools-1.1-SNAPSHOT $ java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment Homebrew (build 21.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)
```

**Comment by wpchen** [comment]
From insvtools.log:

```
2024-03-25 00:08:22 [DEBUG] Command line arguments: cut --start-time=0.100 ../../../src/test/resources/sample.insv
2024-03-25 00:08:22 [INFO ] InsvTools v.1.1-SNAPSHOT, start processing 'cut' command
2024-03-25 00:08:22 [INFO ] Processing sample.insv -> sample.cut.insv
2024-03-25 00:08:22 [DEBUG] Start time has been adjusted by sync samples to new value: 0.0
2024-03-25 00:08:22 [DEBUG] Track sample.insv[1](vide) has been clipped [firstSample=0, lastSample=30]
2024-03-25 00:08:22 [DEBUG] Track sample.insv[2](soun) has been clipped [firstSample=0, lastSample=47]
2024-03-25 00:08:22 [DEBUG] Track sample.insv[3](text) has been clipped [firstSample=0, lastSample=11]
2024-03-25 00:08:22 [DEBUG] Found INSV metadata [framesCount=11]
2024-03-25 00:08:22 [ERROR] Failure: java.nio.BufferOverflowException
java.nio.BufferOverflowException
	at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:744)
	at java.base/java.nio.HeapByteBuffer.putDouble(HeapByteBuffer.java:672)
	at org.insvtools.records.GyroV2Record.write(GyroV2Record.java:32)
	at org.insvtools.frames.TimestampedFrame.writeParsed(TimestampedFrame.java:35)
	at org.insvtools.frames.Frame.write(Frame.java:37)
	at org.insvtools.InsvMetadata.write(InsvMetadata.java:72)
	at org.insvtools.commands.CutCommand.run(CutCommand.java:263)
	at org.insvtools.InsvTools.main(InsvTools.java:111)
```

**Comment by alex-plekhanov** [comment]
@wpchen, thanks for the report. Fixed here https://github.com/alex-plekhanov/insvtools/commit/262aadabc8390baf749bed60ae214b0b0668b6de

**Comment by wpchen** [comment]
Working for me now. Thanks for the quick fix (and this tool in general)!
